### ISSUE TITLE
Suggestion: Bioconda or DockerHub distribution

### ISSUE THREAD

**Issue by Benjamin-Lee** [cusbg/traveler#13]
This looks awesome. I'll install it manually for now, but it makes like a ton easier when there's a prebuilt version I can rely on and download easily.

**Comment by davidhoksza** [comment]
Hi @Benjamin-Lee. You can run Traveler via Docker, check out the README.

**Comment by MingleiYang** [comment]
it is a great tool. however, when I installed it, no matter manually or docker, it come to errors.

$ sudo docker build . -t traveler
Sending build context to Docker daemon  188.9MB
Step 1/6 : FROM gcc:4.9
4.9: Pulling from library/gcc
aa18ad1a0d33: Pull complete 
15a33158a136: Pull complete 
f67323742a64: Pull complete 
c4b45e832c38: Pull complete 
e5d4afe2cf59: Pull complete 
1efbd2d5674a: Pull complete 
022a58c161f7: Pull complete 
6461d3be7619: Pull complete 
Digest: sha256:6356ef8b29cc3522527a85b6c58a28626744514bea87a10ff2bf67599a7474f5
Status: Downloaded newer image for gcc:4.9
 ---> 1b3de68a7ff8
Step 2/6 : COPY . /usr/src/traveler
 ---> 1f3a3437c11d
Step 3/6 : WORKDIR /usr/src/traveler
 ---> Running in 6f2f6e21bcc4
Removing intermediate container 6f2f6e21bcc4
 ---> e4284f819730
Step 4/6 : RUN   cd /usr/src/traveler/src &&   make build
 ---> Running in 60cadef29f9c
****************MAKEFILE-GENERATING:tree****************

make --directory=tree --makefile=Makefile make
make[1]: Entering directory '/usr/src/traveler/src/tree'
make[1]: Leaving directory '/usr/src/traveler/src/tree'

****************END-MAKEFILE-GENERATING:tree****************
****************MAKEFILE-GENERATING:ted****************

make --directory=ted --makefile=Makefile make
make[1]: Entering directory '/usr/src/traveler/src/ted'
make[1]: Leaving directory '/usr/src/traveler/src/ted'

****************END-MAKEFILE-GENERATING:ted****************
****************MAKEFILE-GENERATING:utils****************

make --directory=utils --makefile=Makefile make
make[1]: Entering directory '/usr/src/traveler/src/utils'
make[1]: Leaving directory '/usr/src/traveler/src/utils'

****************END-MAKEFILE-GENERATING:utils****************
****************MAKEFILE-GENERATING:draw****************

make --directory=draw --makefile=Makefile make
make[1]: Entering directory '/usr/src/traveler/src/draw'
make[1]: Leaving directory '/usr/src/traveler/src/draw'

****************END-MAKEFILE-GENERATING:draw****************
****************MAKEFILE-GENERATING:app****************

make --directory=app --makefile=Makefile make
make[1]: Entering directory '/usr/src/traveler/src/app'
make[1]: Leaving directory '/usr/src/traveler/src/app'

****************END-MAKEFILE-GENERATING:app****************
****************MAKEFILE-GENERATING:tests****************

make --directory=tests --makefile=Makefile make
make[1]: Entering directory '/usr/src/traveler/src/tests'
make[1]: Leaving directory '/usr/src/traveler/src/tests'

****************END-MAKEFILE-GENERATING:tests****************
****************COMPILE:****************

make -j2 --directory=./build -f Makefile build
make[1]: Entering directory '/usr/src/traveler/src/build'
g++ -std=gnu++11 -c -g -Wall -I../include/ -I../include/tests/ -DLOG_FILE=\"/tmp/traveler.log\" ../utils/document_writer.cpp -o document_writer.o
g++ -std=gnu++11 -c -g -Wall -I../include/ -I../include/tests/ -DLOG_FILE=\"/tmp/traveler.log\" ../utils/logger.cpp -o logger.o
../utils/document_writer.cpp: In member function 'std::string document_writer::get_rna_background_formatted(tree_base<rna_pair_label>::pre_post_order_iterator, tree_base<rna_pair_label>::pre_post_order_iterator) const':
../utils/document_writer.cpp:425:35: error: 'f' was not declared in this scope
         point diff_orig = p2 - p1;f
                                   ^
../utils/document_writer.cpp:429:14: error: 'tmp' was not declared in this scope
         p1 = tmp;
              ^
g++ -std=gnu++11 -c -g -Wall -I../include/ -I../include/tests/ -DLOG_FILE=\"/tmp/traveler.log\" ../utils/ps_writer.cpp -o ps_writer.o
document_writer.cpp.mk:9: recipe for target 'document_writer.o' failed
make[1]: *** [document_writer.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/src/traveler/src/build'
Makefile:33: recipe for target 'compile' failed
make: *** [compile] Error 2
The command '/bin/sh -c cd /usr/src/traveler/src &&   make build' returned a non-zero code: 2

could you give me some suggestions how to deal with it?

My best,

Minglei
